#get admin logs
test_name: get_admin_logs

stages:
  - name: get_logs
    request:
      url: http://sp.int3.sonata-nfv.eu:32001/api/v2/admin/logs
      method: GET
    response:
      status_code: 200
